security:
#    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\User: 
            algorithm: bcrypt

    providers:
        database_users:
            entity:
                class: App\Entity\User
                property: email
        api_users:
            entity:
                class: App\Entity\APIUser
                property: apiToken

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        contact:
            pattern: ^/contact
            provider: api_users
            guard:
                authenticators:
                    - App\Security\ContactAuthenticator

        admin:
            pattern: ^/app/
            anonymous: true
            provider: database_users
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # = 1 week
                path: /
            logout:
                path: security_logout
            guard:
                authenticators:
                    - App\Security\FormLoginAuthenticator


        api_login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: database_users
            json_login:
                check_path: api_login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure     
                
        api:
            pattern:   ^/api/admin
            stateless: true
            provider: database_users
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

#        main:
#            anonymous: true
#            lazy: true

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true
#    enable_authenticator_manager: true
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    role_hierarchy:
        ROLE_CONTACT: ROLE_CONTACT
        ROLE_USER: ROLE_USER
        ROLE_ADMIN : [ROLE_CONTACT, ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
         - { path: ^/app/admin, roles: ROLE_ADMIN }
         - { path: ^/contact, roles: ROLE_CONTACT }
         - { path: ^/api/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/api/admin,       roles: IS_AUTHENTICATED_FULLY }